 

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export type ExamTarget = { 'jee' : null } |
  { 'neet' : null };
export interface Review {
  'id' : bigint,
  'averageStudyHours' : bigint,
  'biggestDistraction' : string,
  'name' : string,
  'neededFeature' : string,
  'timestamp' : bigint,
  'examTarget' : ExamTarget,
}
export interface _SERVICE {
  'getAllReviews' : ActorMethod<[], Array<Review>>,
  'getReviewById' : ActorMethod<[bigint], Review>,
  'submitReview' : ActorMethod<
    [string, ExamTarget, string, bigint, string],
    undefined
  >,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];