/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const ExamTarget = IDL.Variant({ 'jee' : IDL.Null, 'neet' : IDL.Null });
export const Review = IDL.Record({
  'id' : IDL.Nat,
  'averageStudyHours' : IDL.Nat,
  'biggestDistraction' : IDL.Text,
  'name' : IDL.Text,
  'neededFeature' : IDL.Text,
  'timestamp' : IDL.Int,
  'examTarget' : ExamTarget,
});

export const idlService = IDL.Service({
  'getAllReviews' : IDL.Func([], [IDL.Vec(Review)], ['query']),
  'getReviewById' : IDL.Func([IDL.Nat], [Review], ['query']),
  'submitReview' : IDL.Func(
      [IDL.Text, ExamTarget, IDL.Text, IDL.Nat, IDL.Text],
      [],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const ExamTarget = IDL.Variant({ 'jee' : IDL.Null, 'neet' : IDL.Null });
  const Review = IDL.Record({
    'id' : IDL.Nat,
    'averageStudyHours' : IDL.Nat,
    'biggestDistraction' : IDL.Text,
    'name' : IDL.Text,
    'neededFeature' : IDL.Text,
    'timestamp' : IDL.Int,
    'examTarget' : ExamTarget,
  });
  
  return IDL.Service({
    'getAllReviews' : IDL.Func([], [IDL.Vec(Review)], ['query']),
    'getReviewById' : IDL.Func([IDL.Nat], [Review], ['query']),
    'submitReview' : IDL.Func(
        [IDL.Text, ExamTarget, IDL.Text, IDL.Nat, IDL.Text],
        [],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };